#!/bin/sh
echo "Checking code formatting"
./gradlew app:ktlintFormat --daemon
status=$?

if [ "$status" = 0 ]; then
    echo "No formatting issues were found"
    git add .
    git commit -m "Code formatted with ktlin"
    exit 0
else
    echo 1>&2 "* There are code formatting issues that must be addressed"
    exit 1
fi